# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.OneToOneField(max_length=32, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.TextField(blank=True)),
                ('lastname', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('N', 'unknown')], max_length=1)),
                ('gitURL', models.TextField(blank=True)),
            ],
        ),
    ]
