# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='Eric-PC', max_length=200),
        ),
    ]
