# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to=network.models.user_directory_path)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Author')),
            ],
        ),
    ]
