# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('trusted', models.BooleanField()),
            ],
        ),
    ]
